apiVersion: batch/v1
kind: Job
metadata:
  name: migrate
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: mgrigoriev/kubernetes-rails-example:latest
          command: ['rails']
          args: ['db:migrate']
          envFrom:
            - configMapRef:
                name: env
            - secretRef:
                name: env
