# Production database URL is set via ENV['DATABASE_URL'], which is stored in k8s secret.
# kubectl create secret generic rails-app-secrets \
#   --from-literal=database-url='postgresql://postgres@host.minikube.internal/blog_production?pool=5'

development:
  url: postgresql://localhost/blog_development?pool=5

test:
  url: postgresql://localhost/blog_test?pool=5
