name: Deploy

on:
  push:
    branches:
      - main

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: mgrigoriev/kubernetes-rails-example

      - name: Build and push
        id: docker_push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          file: Dockerfile

      - name: Migrate database
        run: |
          kubectl create -f .k8s/jobs/migrate.yml
          kubectl wait --for=condition=complete --timeout=600s job/migrate
          kubectl delete job migrate

      - name: Restart app
        run: kubectl rollout restart deployment/rails-app

      - name: Restart sidekiq
        run: kubectl rollout restart deployment/sidekiq
